steps:
  - name: Checkout
    uses: actions/checkout@v3
    with:
      persist-credentials: false
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v3
    with:
      semantic_version: 20.0.2
      extra_plugins: |
        @semantic-release/changelog@6.0.2
        @semantic-release/git@10.0.1
    env:
      GITHUB_TOKEN: ${{ secrets.GA_GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GA_NPM_TOKEN }}