on:
  workflow_call:
    secrets:
      GA_GITHUB_TOKEN:
        description: "The GitHub token to use for the release"
        required: true
      GA_NPM_TOKEN:
        description: "The NPM token to use for the release"
        required: true
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Run Semantic Release action
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 20.0.2
          extra_plugins: |
            @semantic-release/changelog@6.0.2
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GA_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GA_NPM_TOKEN }}
