on: push

jobs:
  release_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v3
      - name: Release using Semantic Release
        uses: ./.github/workflows/release.yaml
        secrets:
          GA_GITHUB_TOKEN: ${{ secrets.GA_GITHUB_TOKEN }}
          GA_NPM_TOKEN: ${{ secrets.GA_NPM_TOKEN }}